# Generated by Django 4.2 on 2024-04-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(default='497504', max_length=6, verbose_name='Код'),
        ),
    ]
