# Generated by Django 5.0.2 on 2024-03-13 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'permissions': [('set_active', 'Can active client')],
            },
        ),
        migrations.CreateModel(
            name='SendingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_first_sending', models.DateTimeField(verbose_name='Время первой отправки')),
                ('periodicity', models.CharField(max_length=100, verbose_name='Периодичность отправки')),
                ('status', models.CharField(default='Создана', max_length=50, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True)),
                ('clients', models.ManyToManyField(to='main.client', verbose_name='Клиенты для рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('set_active', 'Can active sending')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('message', models.TextField(max_length=500, verbose_name='Тело письма')),
                ('sending_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sendingmessage', verbose_name='Отправка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('attempt_status', models.BooleanField(verbose_name='Cтатус попытки')),
                ('server_response', models.CharField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиент рассылки')),
                ('sending_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sendingmessage', verbose_name='Отправка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
    ]
