# Generated by Django 5.0.2 on 2024-04-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sending_list',
        ),
        migrations.AddField(
            model_name='sendingmessage',
            name='message_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='Сообщение'),
        ),
    ]
