# Generated by Django 5.0.2 on 2024-04-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_message_sending_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingmessage',
            name='periodicity',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], max_length=100, verbose_name='Периодичность отправки'),
        ),
        migrations.AlterField(
            model_name='sendingmessage',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=50, verbose_name='Статус рассылки'),
        ),
    ]
