# Generated by Django 4.2 on 2024-04-17 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sendingmessage_options_client_is_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingmessage',
            name='time_next_sending',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата следующей отправки'),
        ),
    ]
